version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
