# Generated by Django 5.0.3 on 2024-03-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protagonists', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('coming_up', 'Coming Up'), ('starting', 'Starting'), ('running', 'Running'), ('finished', 'Finished')], max_length=20)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
